export const DEFAULT_PRESET_CHANNELS = [
  { id: 'ch-1', number: 1, name: 'TRT 1 HD', type: 'TV', category: 'Ulusal', frequency: 11054, symbolRate: 30000, polarization: 'V', serviceId: 10101, satellite: 'Türksat 42.0°E', favorite: true, locked: false },
  { id: 'ch-2', number: 2, name: 'ATV HD', type: 'TV', category: 'Ulusal', frequency: 12053, symbolRate: 27500, polarization: 'H', serviceId: 10201, satellite: 'Türksat 42.0°E', favorite: true, locked: false },
  { id: 'ch-3', number: 3, name: 'KANAL D HD', type: 'TV', category: 'Ulusal', frequency: 12245, symbolRate: 27500, polarization: 'H', serviceId: 10301, satellite: 'Türksat 42.0°E', favorite: true, locked: false },
  { id: 'ch-4', number: 4, name: 'SHOW TV HD', type: 'TV', category: 'Ulusal', frequency: 12209, symbolRate: 10000, polarization: 'H', serviceId: 10401, satellite: 'Türksat 42.0°E', favorite: true, locked: false },
  { id: 'ch-5', number: 5, name: 'STAR TV HD', type: 'TV', category: 'Ulusal', frequency: 12015, symbolRate: 27500, polarization: 'H', serviceId: 10501, satellite: 'Türksat 42.0°E', favorite: true, locked: false },
  { id: 'ch-6', number: 6, name: 'TV8 HD', type: 'TV', category: 'Eğlence', frequency: 12356, symbolRate: 7100, polarization: 'H', serviceId: 10601, satellite: 'Türksat 42.0°E', favorite: true, locked: false },
  { id: 'ch-7', number: 7, name: 'NOW TV HD', type: 'TV', category: 'Ulusal', frequency: 12329, symbolRate: 6666, polarization: 'H', serviceId: 10701, satellite: 'Türksat 42.0°E', favorite: true, locked: false },
  { id: 'ch-8', number: 8, name: 'HABERTÜRK HD', type: 'TV', category: 'Haber', frequency: 12209, symbolRate: 10000, polarization: 'H', serviceId: 10801, satellite: 'Türksat 42.0°E', favorite: false, locked: false },
  { id: 'ch-9', number: 9, name: 'NTV HD', type: 'TV', category: 'Haber', frequency: 12015, symbolRate: 27500, polarization: 'H', serviceId: 10901, satellite: 'Türksat 42.0°E', favorite: false, locked: false },
  { id: 'ch-10', number: 10, name: 'CNN TÜRK HD', type: 'TV', category: 'Haber', frequency: 12245, symbolRate: 27500, polarization: 'H', serviceId: 11001, satellite: 'Türksat 42.0°E', favorite: false, locked: false },
  { id: 'ch-11', number: 11, name: 'beIN SPORTS HABER', type: 'TV', category: 'Spor', frequency: 12379, symbolRate: 30000, polarization: 'V', serviceId: 11101, satellite: 'Türksat 42.0°E', favorite: true, locked: false },
  { id: 'ch-12', number: 12, name: 'TRT SPOR HD', type: 'TV', category: 'Spor', frequency: 11054, symbolRate: 30000, polarization: 'V', serviceId: 11201, satellite: 'Türksat 42.0°E', favorite: true, locked: false },
  { id: 'ch-13', number: 13, name: 'A HABER HD', type: 'TV', category: 'Haber', frequency: 12053, symbolRate: 27500, polarization: 'H', serviceId: 11301, satellite: 'Türksat 42.0°E', favorite: false, locked: false },
  { id: 'ch-14', number: 14, name: 'SÖZCÜ TV HD', type: 'TV', category: 'Haber', frequency: 12685, symbolRate: 30000, polarization: 'V', serviceId: 11401, satellite: 'Türksat 42.0°E', favorite: true, locked: false },
  { id: 'ch-15', number: 15, name: 'HALK TV HD', type: 'TV', category: 'Haber', frequency: 12685, symbolRate: 30000, polarization: 'V', serviceId: 11501, satellite: 'Türksat 42.0°E', favorite: false, locked: false },
  { id: 'ch-16', number: 16, name: 'TRT ÇOCUK HD', type: 'TV', category: 'Çocuk', frequency: 11054, symbolRate: 30000, polarization: 'V', serviceId: 11601, satellite: 'Türksat 42.0°E', favorite: true, locked: false },
  { id: 'ch-17', number: 17, name: 'MİNİKA GO', type: 'TV', category: 'Çocuk', frequency: 12053, symbolRate: 27500, polarization: 'H', serviceId: 11701, satellite: 'Türksat 42.0°E', favorite: false, locked: false },
  { id: 'ch-18', number: 18, name: 'TLC HD', type: 'TV', category: 'Eğlence', frequency: 12015, symbolRate: 27500, polarization: 'H', serviceId: 11801, satellite: 'Türksat 42.0°E', favorite: false, locked: false },
  { id: 'ch-19', number: 19, name: 'DMAX HD', type: 'TV', category: 'Eğlence', frequency: 12015, symbolRate: 27500, polarization: 'H', serviceId: 11901, satellite: 'Türksat 42.0°E', favorite: false, locked: false },
  { id: 'ch-20', number: 20, name: 'TRT FM', type: 'RADYO', category: 'Radyo', frequency: 11054, symbolRate: 30000, polarization: 'V', serviceId: 20101, satellite: 'Türksat 42.0°E', favorite: false, locked: false },
  { id: 'ch-21', number: 21, name: 'KRAL FM', type: 'RADYO', category: 'Radyo', frequency: 12015, symbolRate: 27500, polarization: 'H', serviceId: 20201, satellite: 'Türksat 42.0°E', favorite: false, locked: false },
  { id: 'ch-22', number: 22, name: 'POWER FM', type: 'RADYO', category: 'Radyo', frequency: 12265, symbolRate: 27500, polarization: 'V', serviceId: 20301, satellite: 'Türksat 42.0°E', favorite: false, locked: false }
];
